authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
  path('login/', authapp.login, name='login'),
  path('logout/', authapp.logout, name='logout'),
  path('register/', authapp.register, name='register'),
  path('edit/', authapp.edit, name='edit'),
]

basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
  path('', basketapp.basket, name='basket'),
  path('add/<int:pk>/', basketapp.basket_add, name='basket_add'),
  path('remove/<int:pk>)/', basketapp.basket_remove, name='remove')
]

watch/urls.py
from django.contrib import admin
from django.urls import path, include
from mainapp import views as mainapp
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', mainapp.index, name="main"),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basketapp')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/models.py
from django.db import models

from django.db import models
from django.contrib.auth.models import AbstractUser

class ShopUser(AbstractUser):
  avatar = models.ImageField(upload_to="users_avatars", blank=True)
  age = models.PositiveIntegerField(verbose_name="age", null=True, blank=True)

basketapp/models.py
from django.db import models
from django.db import models
from django.conf import settings
from mainapp.models import Product

class Basket(models.Model):
  user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='basket')
  product = models.ForeignKey(Product, on_delete=models.CASCADE)
  quantity = models.PositiveIntegerField(verbose_name='количество', default=0)
  add_datetime = models.DateTimeField(verbose_name='время', auto_now_add=True)

mainapp/models.py
from django.db import models
  
class ProductCategory(models.Model):
  name = models.CharField(verbose_name='имя', max_length=64, unique=True)
  description = models.TextField(verbose_name='описание', blank=True)
  def __str__(self):
    return self.name

class Product(models.Model):
  category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
  name = models.CharField(max_length=150, verbose_name="Name")
  image = models.ImageField(blank=True, upload_to='products')
  description = models.TextField(verbose_name="description")
  price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="price", default=0)
  quantity = models.PositiveIntegerField(default=0, verbose_name="quantity")
  
  def __str__(self):
    return f"{self.name} ({self.category.name})"

authapp/forms.py
from typing import Any
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .models import ShopUser

class ShopUserLoginForm(AuthenticationForm):
  class Meta:
    model = ShopUser
    fields = ('username', 'password')

  def __init__(self, *args, **kwargs):
    super(ShopUserLoginForm, self).__init__(*args, **kwargs)
    self.fields["username"].widget.attrs["placeholder"] = "login"
    self.fields["password"].widget.attrs["placeholder"] = "password"
    for field_name, field in self.fields.items():
        field.widget.attrs['class'] = 'input_admin_login'

class ShopUserRegistrForm(UserCreationForm):
  class Meta:
    model = ShopUser
    fields = ('username', 'first_name', 'password1', 'password2', 'email', 'age', 'avatar')
  
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    placeholder_list = {'username':'username', 'first_name':'first_name', 'password1':'password', 'password2':'password again', 'email':'email', 'age':'age', 'avatar':'avatar'}
    for name, placeholder in placeholder_list.items():
      self.fields[name].widget.attrs["placeholder"] = placeholder
    for fieald_name, field in self.fields.items():
      field.widget.attrs['class'] = 'menu_item_element'
      field.help_text = ''
  
  # def clean_age(self):
  #   data = self.cleaned_data['age']
  #   if data < 18:
  #     raise forms.ValidationError("Вы слишком молоды!")
  #   return data

    

authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from authapp.forms import ShopUserLoginForm, ShopUserRegistrForm
from django.contrib import auth
from django.urls import reverse


def login(request):
  title = "login"

  login_form = ShopUserLoginForm(data=request.POST)
  if request.method == 'POST' and login_form.is_valid():
    username = request.POST['username']
    password = request.POST['password']

    user = auth.authenticate(username=username, password=password)
    if user and user.is_active:
      auth.login(request, user)
      return HttpResponseRedirect(reverse('main'))
    
  content = {'title': title, 'login_form':login_form}
  return render(request, 'authapp/login.html', content)

def logout(request):
  auth.logout(request)
  return HttpResponseRedirect(reverse('main'))

def register(request):
  title = 'Регистрация'

  if request.method == "POST":
    register_form = ShopUserRegistrForm(request.POST, request.FILES)

    if register_form.is_valid():
      register_form.save()
      return HttpResponseRedirect(reverse('authapp:login'))
  else:
    register_form = ShopUserRegistrForm()
  context = {
    'title':title,
    'register_form': register_form
  }

  return render(request, 'authapp/register.html', context)

def edit(request):
  return HttpResponseRedirect(reverse('main'))

basketapp/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from basketapp.models import Basket
from mainapp.models import Product


def basket(request):
  context = {
    'basket_list': Basket.objects.filter(user=request.user)
  }
  return render(request, 'basketapp/basket.html', context)

def basket_add(request, pk):
  product_item = get_object_or_404(Product, pk=pk)
  basket_item = Basket.objects.filter(user=request.user, product=product_item).first()

  if not basket_item:
    basket_item = Basket(user=request.user, product=product_item)

  basket_item.quantity += 1
  basket_item.save()
  return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def basket_remove(request, pk):
  content = {}
  return render(request, 'basketapp/basket.html', content)

mainapp/views.py
from django.shortcuts import render
from django.shortcuts import render
from mainapp.models import Product, ProductCategory
from basketapp.models import Basket

def index(request, pk=None):
  product_list = Product.objects.all()
  product_category = ProductCategory.objects.all()
  
  basket = []
  if request.user.is_authenticated:
    basket = Basket.objects.filter(user=request.user)

  if pk:
    if pk == '0':
      product_list = Product.objects.all().order_by('price')
      
  else:
    
    products = Product.objects.filter(category__pk=pk).order_by('price')
  context = {
    'products': product_list,
    'product_category': product_category,
    'basket': basket
  }

  return render(request, 'mainapp/index.html', context)

authapp/templates/authapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Playfair+Display:ital@0;1&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/reset.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %} ">
  {% block extra_style %}
  {% endblock %}
</head>
<body>
{% block content%}
{% endblock %}
</body>
</html>

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}
{% block extra_style %}
  <link rel="stylesheet" href="{% static 'css/style_login.css' %}">
{% endblock %}
{% block content %}
  <div class="authorization">
    <div class="container">
      <div class="auth_inner">
        <div class="login">
          <h2 class="h2 text-center head">
          Вход в систему
          </h2>
        </div>
        {% csrf_token %}
        <form  method="POST" class="adminlogin">
          {% csrf_token %}
          <div class="login">
            {{ login_form.username }}
          </div>
          <div class="password">
            {{ login_form.password }}
          </div>
          <div class="login__button">
            <button class="button__item">
              <a href="{% url 'auth:login' %}" class="button_item_link">Sign in</a> 
            </button>
            <button class="button__item" >
              <a href="{% url 'auth:register' %}" class="button_item_link">Sign up</a> 
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load static %}
{% block extra_style %}
  <link rel="stylesheet" href="{% static 'css/style_login.css' %}">
{% endblock %}
{% block content %}
  <div class="authorization">
    <div class="container">
      <div class="auth_inner">
        <div class="login">
          <h2 class="h2 text-center head">
          Регистрация
          </h2>
        </div>
        {% csrf_token %}
        <form  method="POST" class="adminlogin"  enctype="multipart/form-data">
          
          <ul class="registr_menu">
            {% csrf_token %}
            <li class="menu_item">
              {{ register_form.username }}
            </li>
            <li class="menu_item">
              {{ register_form.first_name }}
            </li>
            <li class="menu_item">
              {{ register_form.password1 }}
            </li>
            <li class="menu_item">
              {{ register_form.password2 }}
            </li>
            <li class="menu_item">
              {{ register_form.email }}
            </li>
            <li class="menu_item">
              {{ register_form.age }}
            </li>
            <li class="menu_item">
              <div class="avavtar">
                {{ register_form.avatar }}
              </div>
              
            </li>
          
          </ul>
          <div class="login__button">
            <input class="button__item" type="submit" value="Sign up">
            <button class="button__item" >
              <a href="{% url 'auth:login' %}" class="button_item_link">Back</a> 
            </button>
          </div>
          
        </form>
        
       
      </div>
    </div>
  </div>
{% endblock %}